# Generated by Django 5.0.2 on 2024-03-02 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.division')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_required', models.TimeField()),
                ('responsible_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.division')),
                ('responsible_sub_divifany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.division')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_divifany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedProblems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_problem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem_solved_state', models.BooleanField(default=False)),
                ('current_responsible_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.division')),
                ('current_responsible_sub_divifany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.subdivision')),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.problemtype')),
                ('user_submitted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.PositiveIntegerField(choices=[(1, 'AUDIO'), (2, 'VIDEO'), (3, 'IMAGE')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evdc', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.submittedproblems')),
            ],
        ),
        migrations.CreateModel(
            name='TrackProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_since_submission', models.TimeField()),
                ('current_responsible_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.division')),
                ('current_responsible_sub_divifany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.subdivision')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grivance_managent.submittedproblems')),
            ],
        ),
    ]
