# Generated by Django 5.0.2 on 2024-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grivance_managent', '0002_alter_division_admin_alter_subdivision_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtype',
            name='time_required',
            field=models.DurationField(),
        ),
    ]
