# Generated by Django 5.0.2 on 2024-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grivance_managent', '0003_alter_problemtype_time_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemevidence',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemevidence',
            name='file_type',
            field=models.PositiveIntegerField(choices=[(1, 'AUDIO'), (2, 'VIDEO'), (3, 'IMAGE'), (4, 'PDF')], default=3),
        ),
    ]
