# Generated by Django 5.0.2 on 2024-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Responsible Personal'), (2, 'Student with grivance'), (3, 'Division Admin'), (4, 'Sub_division admin')], default=2),
        ),
    ]
